spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/restaurant?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mirinae
    password: mirinae123!

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update